### PR TITLE
fix(cosh): validate openai api key and model via /models endpoint on auth

### LINKED ISSUE #213: [cosh]bug:openai 认证apikey输入错误确认后提示认证成功
### Component

cosh

### Bug Description

 ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
  │ >_ Copilot Shell (v2.0.3)                                                                                                                                                                                     │
  │                                                                                                                                                                                                               │
  │ OpenAI | qwen3-coder-plus (/auth to change)                                                                                                                                                                   │
  │ ~                                                                                                                                                                                                             │
  ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
  Tips: You can resume a previous conversation by running co/copilot --continue or co/copilot --resume.

  > /auth

  **ℹ Authenticated successfully with openai credentials.**

  > /model


╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ You are running Copilot Shell in your home directory. It is recommended to run in a project-specific directory. Use "/dir cd <path>" to switch to a project directory.                                            │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

  ╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
  │                                                                                                  │
  │ Select Model                                                                                     │
  │                                                                                                  │
  │ Current (effective) configuration                                                                │
  │                                                                                                  │
  │ AuthType:   openai                                                                               │
  │ Model:      qwen3-coder-plus                                                                     │
  │             Programmatic updateCredentials                                                       │
  │ Base URL:   https://dashscope.aliyuncs.com/compatible-mode/v1                                    │
  │             Programmatic updateCredentials                                                       │
  │ API Key:    (set)                                                                                │
  │             Programmatic updateCredentials                                                       │
  │                                                                                                  │
  │   1. [qwen-oauth] coder-model                                                                    │
  │      The latest Qwen Coder model from Alibaba Cloud ModelStudio (version:                        │
  │      qwen3-coder-plus-2025-09-23)                                                                │
  │   2. [qwen-oauth] vision-model                                                                   │
  │      The latest Qwen Vision model from Alibaba Cloud ModelStudio (version:                       │
  │      qwen3-vl-plus-2025-09-23)                                                                   │
  │ ● 3. [openai] qwen3-coder-plus                                                                   │
  │      已通过 /auth 配置                                                                           │
  │                                                                                                  │
  │ (Press Esc to close)                                                                             │
  │                                                                                                  │
  ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

### Steps to Reproduce

1. /auth Custom Provider 
2. 任意选择一个：输入apikey随机几个值
3. 提示认证成功

### Expected Behavior

认证失败

### Environment

alinux4 ecs

### Relevant Log Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kongld-mq**
fix(cosh): validate openai api key and model via /models endpoint on auth

- Add validateApiKey() method using models.retrieve(model) API (zero token cost)

## Description

When a user enters an incorrect API key via /auth with a Custom Provider 
(OpenAI-compatible endpoint), the system incorrectly shows "Authenticated 
successfully". This happens because the authentication flow only creates the 
client object without verifying the credentials against the server.
﻿
The fix adds a validateApiKey() method to OpenAIContentGenerator that calls 
the /models endpoint during authentication. If the server returns HTTP 401, 
an "Invalid API key" error is shown. If the endpoint returns a model list that 
does not include the configured model, a "Model not available" error is shown. 
If /models returns an empty list (provider doesn't expose models), model 
validation is skipped to support such providers. Validation errors are displayed 
in the OpenAIKeyPrompt UI instead of returning to AuthDialog, allowing users to 
retry directly.

## Related Issue

closes #213 

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring (no functional change)
- [ ] Performance improvement
- [ ] CI/CD or build changes

## Scope

- [x] `cosh` (copilot-shell)
- [ ] `sec-core` (agent-sec-core)
- [ ] `skill` (os-skills)
- [ ] `sight` (agentsight)
- [ ] Multiple / Project-wide

## Checklist

- [ ] I have read the [Contributing Guide](../CONTRIBUTING.md)
- [ ] My code follows the project's code style
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the documentation accordingly
- [ ] For `cosh`: Lint passes, type check passes, and tests pass
- [ ] For `sec-core` (Rust): `cargo clippy -- -D warnings` and `cargo fmt --check` pass
- [ ] For `sec-core` (Python): Ruff format and pytest pass
- [ ] For `skill`: Skill directory structure is valid and shell scripts pass syntax check
- [ ] For `sight`: `cargo clippy -- -D warnings` and `cargo fmt --check` pass
- [ ] Lock files are up to date (`package-lock.json` / `Cargo.lock`)

## Additional Notes

The validation uses models.list() API which is free and doesn't consume tokens. 
For providers that return an empty model list (don't expose /models), model 
validation is skipped to ensure compatibility. Authentication errors (401, 403, 
429, network issues) and model-not-found errors are shown in the OpenAIKeyPrompt 
UI, allowing users to correct input and retry without returning to AuthDialog.

### CODE REVIEW

File: src/copilot-shell/packages/core/src/core/openaiContentGenerator/openaiContentGenerator.ts [hunk 1]
```diff
@@ -62,6 +63,90 @@ export class OpenAIContentGenerator implements ContentGenerator {
...
+
+      // Check if the configured model exists in the available models list
+      const modelExists = availableModels.some((m) => m.id === model);
+
+      if (!modelExists) {
+        // Model not found in available models list
+        // Show simple error without listing all models (could be too many)
+        return Promise.reject(
+          new Error(
+            `Model "${model}" is not available. Please check if the model name is correct.`,
```
Comment (kongche-jbw) [inline src/copilot-shell/packages/core/src/core/openaiContentGenerator/openaiContentGenerator.ts]: 错误消息没有使用翻译。建议统一处理

File: src/copilot-shell/packages/core/src/core/openaiContentGenerator/openaiContentGenerator.ts [hunk 2]
```diff
@@ -62,6 +63,90 @@ export class OpenAIContentGenerator implements ContentGenerator {
...
+  getContentGeneratorConfig(): ContentGeneratorConfig {
+    return this.pipeline.getContentGeneratorConfig();
+  }
+
+  /**
+   * Format authentication error messages for user-friendly display
+   * @param error The error from API call
+   * @returns Formatted Error with user-friendly message
+   */
+  private formatAuthError(error: unknown): Error {
```
Comment (kongche-jbw) [inline src/copilot-shell/packages/core/src/core/openaiContentGenerator/openaiContentGenerator.ts:122]: 同上，统一进行下翻译的处理

File: src/copilot-shell/packages/core/src/core/openaiContentGenerator/openaiContentGenerator.ts [hunk 3]
```diff
@@ -62,6 +63,90 @@ export class OpenAIContentGenerator implements ContentGenerator {
...
+   * @returns Promise<void> - resolves if both valid, rejects if either invalid
+   */
+  async validateApiKey(): Promise<void> {
+    try {
+      const openai = this.pipeline.getProvider().buildClient();
+      const model = this.pipeline.getContentGeneratorConfig().model;
+
+      // Make a simple API call to validate the key and get available models
+      // Using models.list() as it's lightweight and doesn't consume tokens
+      const modelsResponse = await openai.models.list();
```
Comment (samchu-zsl) [inline src/copilot-shell/packages/core/src/core/openaiContentGenerator/openaiContentGenerator.ts]: openai.models.list() 只返回一个分页的 CursorPage 对象。直接访问 .data 只能获取第一页结果。如果模型过多导致分页，配置的模型可能在后续页面中，用户看到 "Model ... is not available" 的误报错误。

尝试 models.retrieve(model) 替代 models.list() 能否解决分页问题

File: src/copilot-shell/packages/core/src/core/openaiContentGenerator/openaiContentGenerator.ts [hunk 4]
```diff
@@ -62,6 +63,90 @@ export class OpenAIContentGenerator implements ContentGenerator {
...
 
+  /**
+   * Validate API key and model availability by calling models.list() API.
+   * This validates:
+   * 1. API key is valid (returns 401 if invalid)
+   * 2. Configured model is available (checks if model exists in returned list)
+   * Uses models.list() as it's lightweight and doesn't consume tokens.
+   * @returns Promise<void> - resolves if both valid, rejects if either invalid
+   */
+  async validateApiKey(): Promise<void> {
```
Comment (samchu-zsl) [inline src/copilot-shell/packages/core/src/core/openaiContentGenerator/openaiContentGenerator.ts:75]: 需要补充 validateApiKey 测试用例

**Review by samchu-zsl — CHANGES_REQUESTED** [review]

**Review by samchu-zsl — APPROVED** [review]
LGTM, thx!
